apiVersion: v1
kind: Service
metadata:
  name: ghost-blog-CONFIG_APP_NAME
  namespace: CONFIG_NAMESPACE
spec:
  selector:
    app: ghost-blog-CONFIG_APP_NAME
  ports:
  - protocol: TCP
    port: 80
    targetPort: 2368
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: blog-content-CONFIG_APP_NAME
   namespace: CONFIG_NAMESPACE
spec:
   accessModes:
   - ReadWriteOnce
   resources:
     requests:
       storage: 10Gi
   storageClassName: linode-block-storage-retain
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: ghost-blog-CONFIG_APP_NAME
    namespace: CONFIG_NAMESPACE
    labels:
        app: ghost-blog
spec:
    replicas: 1
    selector:
        matchLabels:
            app: ghost-blog-CONFIG_APP_NAME
    template:
        metadata:
            labels:
                app: ghost-blog-CONFIG_APP_NAME
        spec:
            containers:
            - name: ghost-blog-CONFIG_APP_NAME
              image: ghost:4
              imagePullPolicy: Always
              ports:
                - containerPort: 2368
              env:
                - name: url
                  value: CONFIG_PRIMARY_URL
                - name: database__client
                  value: mysql
                - name: database__connection__host
                  valueFrom:
                    secretKeyRef:
                      name: ghost-secrets-CONFIG_APP_NAME
                      key: dbhost
                - name: database__connection__user
                  valueFrom:
                    secretKeyRef:
                      name: ghost-secrets-CONFIG_APP_NAME
                      key: dbuser
                - name: database__connection__password
                  valueFrom:
                    secretKeyRef:
                      name: ghost-secrets-CONFIG_APP_NAME
                      key: dbpassword
                - name: database__connection__database
                  valueFrom:
                    secretKeyRef:
                      name: ghost-secrets-CONFIG_APP_NAME
                      key: dbname
              volumeMounts:
              - mountPath: /var/lib/ghost/content
                name: blog-content
            volumes:
            - name: blog-content
              persistentVolumeClaim:
                claimName: blog-content-CONFIG_APP_NAME

