# Don't store your real secrets in git. 
# Put them in your Password Keeper
# This file is here as an example 

apiVersion: v1
kind: Secret
metadata:
  name: ghost-secrets-CONFIG_APP_NAME
  namespace: CONFIG_NAMESPACE
type: Opaque
stringData:
  dbhost: yourDbServer        #I like to use an internal IP
  dbname: yourDbName
  dbuser: yourDbUser
  dbpassword: yourDbPassword

